/*
Languages = {
    spanish: {
        login: 'Ingresar',
        signup: 'Registrarse',
        email: 'Correo',
        password: 'Contraseña',
        name: 'Nombre(s)',
        lastname: 'Apellido(s)',
        repeatPassword: 'Repite tu contraseña',
        secCode: '',
        topics: '',
        history: '',
        missignSessions: '',
        addCustomizedReviews: '',
        logOut: '',
        nextReviews: '',
        tomorrow: '',
        today: '',
        addNewSession: '',
        topic: '',
        date: '',
        review: '',
        openCalendar: '',
        references: '',
        january: '',
        february: '',
        march: '',
        april: '',
        may: '',
        june: '',
        july: '',
        august: '',
        september: '',
        october: '',
        november: '',
        december: '',
        add: '',
        tip: '',
        delete: '',
        edit: '',
        deleteCompletedTopics: '',
        hideCompletedTopics: '',
        cleanHistory: '',
        editTopic: '',

    },
    english: {
        login: 'Login',
        signup: 'Signup'
    }
}
*/