let Languages = {
    es: {
        langs: {
            spanish: 'Español',
            english: 'Inglés'
        },
        tips: [
            "Puedes añadir repasos personalizados desde configuración",
            "Nunca te rindas:)",
            "En referencias puedes incluir tus referencias donde estudiaste o hacer anotaciones del tema",
            "No hagas más de 3 sesiones nuevas a la semana para no acumular tantos repasos en un día",
            "En el calendario puedes ver todos los repasos pendientes, en la sección \"Próximos repasos\" solo puedes ver los próximos 20 repasos",
            "Si marcaste como completado un repaso por accidente puedes arreglarlo en la pestaña de historial",
            "En la pestaña \"Mis temas\" puedes editar la fecha de los repasos y todo lo relacionado con un tema registrado",
            "Nunca dejes de aprender",
            "Puedes ver las referencias de un tema presionando el botón \"Editar\" en la pestaña de \"Mis temas\" o presionando el icono de libro en próximos repasos",
            "Si tienes muchos repasos acumulados para un día los puedes reagendar la pestaña \"Mis temas\""
        ],
        login: 'Ingresar',
        signup: 'Regístrate',
        email: 'Correo',
        password: 'Contraseña',
        name: 'Nombre',
        lastname: 'Apellido(s)',
        repeatYourPassword: 'Repite tu contraseña',
        myTopics: 'Mis temas',
        history: 'Historial',
        missedSessions: 'Sesiones perdidas',
        addCustomizedReviews: 'Añadir repasos personalizados',
        logOut: 'Cerrar sesión',
        upcomingReviews: 'Próximos repasos',
        tomorrow: 'Mañana',
        seeReferences: 'Ver referencias',
        today: 'Hoy',
        addNewStudySession: 'Registrar nueva sesión de estudio',
        topic: 'Tema',
        date: 'Fecha',
        review: 'Repaso',
        reviews: 'Repasos',
        default: 'Predeterminado',
        noReviews: 'Sin repasos',
        add: 'Añadir',
        openCalendar: 'Abrir calendario',
        references: 'Referencias',
        january: 'Enero',
        february: 'Febrero',
        march: 'Marzo',
        april: 'Abril',
        may: 'Mayo',
        june: 'Junio',
        july: 'Julio',
        august: 'Agosto',
        september: 'Septiembre',
        october: 'Octubre',
        november: 'Noviembre',
        december: 'Diciembre',
        tip: 'Tip',
        delete: 'Borrar',
        edit: 'Editar',
        deleteCompletedTopics: 'Borrar temas completados',
        hideCompletedTopics: 'Ocultar temas completados',
        cleanHistory: 'Limpiar historial',
        reschedule: 'Reagendar',
        done: 'Listo',
        areYouSureYouWantToDeleteYourHistory: '¿Seguro que quieres borrar tu historial?',
        deleteHistoryWarningMessage: '(Esto eliminará los repasos que ya hayas hecho de tu historial y del registro del tema al que pertenezca)',
        noGoBack: 'No, regresar',
        yesDelete: 'Si, borrar',
        enterTheNewDate: 'Ingresa la nueva fecha',
        areYouSureYouWantToDeleteYourMissedSessions: '¿Seguro que quieres borrar tus sesiones perdidas?',
        deleteMissedSessionsWarningMessage: '(Esto eliminará permanentemente los repasos que no hiciste y no los podrás hacer en el futuro)',
        pleaseEnterAName: 'Por favor, ingresa un nombre',
        invalidNumberOfReviews: 'Cantidad de repasos inválida',
        addCustomizedReviewsMessage: "Aquí puedes añadir repasos personalizados para los temas que hayas estudiado, simplemente tienes que especificar el número de repasos que quieras hacer y después señalar cada cuándo quieres hacer los repasos. Por ejemplo, si quieres repasar todos los días por una semana tendrías especificar que son 7 repasos y luego poner los siguientes números: 1,2,3,4,5,6,7.",
        addCustomizedReviewsWarning: 'Estos repasos serán añadidos permanentemente en tu lista de repasos',
        numberOfReviews: 'Número de repasos',
        areYouSureYouWantToDeleteThisTopic: '¿Seguro que quieres borrar este tema?',
        deleteTopicWarning: '(Esto eliminará permanentemente este tema junto con sus referencias y sus respectivos repasos)',
        ref: 'Referencias',
        areYouSureYouWantToDeleteYourCompletedTopics: '¿Seguro que queires eliminar tus temas completados?',
        deleteCompletedTopicsWarning: '(Esto eliminará permanentemente los temas los cuales todos sus repasos ya hayan sido completados)',
        deleteHistory: 'Eliminar historial',
        deleteMissedSessions: 'Borrar repasos perdidos',
        completedReview: 'Repaso realizado' ,
        initialStudySession: 'Sesión deestudio inicial',
        reviewToBeDone: 'Repaso por realizar',
        reviewNotDone: 'Repaso no realizado',
        pomodoroTimer: 'Temporizador Pomodoro',
        focus: 'Concéntrate',
        sessionsToBeDone: 'Sesiones a realizar',
        focusTime: 'Tiempo de concentración',
        shortRest: 'Descanso corto',
        longRest: 'Descanso largo',
        sessionsBeforeLongRest: 'Sesiones antes del descanso largo'
    },
    en: {
        langs: {
            spanish: 'Spanish',
            english: 'English'
        },
        tips: [
            "You can add customized reviews!",
            "Never surrender:)",
            "In references you can include the references where you studied or you can make notes about the topic",
            "Never do more than 3 sessions each week because you can get very busy",
            "At the calendar you can see your pending reviews, at the \"Upcoming reviews\" you can only see the next 20 reviews",
            "If you marked as completed a review you can undo it at the history section",
            "At the \"My topics\" section you can edit the date of your reviews and everything about a topic",
            "Keep learning",
            "You can see the references of a certain topic pressing at the \"Edit\" button in the \"My topics\" section or pressing at the book icon in the \"Upcoming reviews\" section\"",
            "If you have a lot of reviews acumulated you can reschedule them at the \"My topics\" section",
        ],
        login: 'Log in',
        signup: 'Sign up',
        email: 'Email',
        password: 'Password',
        name: 'Name',
        lastname: 'Lastname',
        repeatYourPassword: 'Repeat your password',
        myTopics: 'My topics',
        history: 'History',
        missedSessions: 'Missed sessions',
        addCustomizedReviews: 'Add customized reviews',
        logOut: 'Log out',
        upcomingReviews: 'Upcoming reviews',
        tomorrow: 'Tomorrow',
        seeReferences: 'See references',
        today: 'Today',
        addNewStudySession: 'Add new study session',
        topic: 'Topic',
        date: 'Date',
        review: 'Review',
        reviews: 'Reviews',
        default: 'Default',
        noReviews: 'No reviews',
        add: 'Add',
        openCalendar: 'Open Calendar',
        references: 'References (Optional)',
        january: 'January',
        february: 'February',
        march: 'March',
        april: 'April',
        may: 'May',
        june: 'June',
        july: 'July',
        august: 'August',
        september: 'September',
        october: 'October',
        november: 'November',
        december: 'December',
        tip: 'Tip',
        delete: 'Delete',
        edit: 'Edit',
        deleteCompletedTopics: 'Delete completed topics',
        hideCompletedTopics: 'Hide completed topics',
        cleanHistory: 'Clean history',
        reschedule: 'Reschedule',
        done: 'Done',
        areYouSureYouWantToDeleteYourHistory: 'Are you sure you want to delete your history?',
        deleteHistoryWarningMessage: '(This will remove the reviews you have already done from your history and from the corresponding topic)',
        noGoBack: 'No, go back',
        yesDelete: 'Yes, delete',
        enterTheNewDate: 'Enter the new date',
        areYouSureYouWantToDeleteYourMissedSessions: 'Are you sure you want yo delete your missed sessions?',
        deleteMissedSessionsWarningMessage: "(This will remove permanently your missed sessions and you won't be able to do them in the future)",
        pleaseEnterAName: 'Please enter a name',
        invalidNumberOfReviews: 'Invalid number of reviews',
        addCustomizedReviewsMessage: "Here you can add customized reviews for the topics you have studied, you just have to specify the number of reviews you want to do and then you have to indicate when you want to do the reviews. E.g., if you want to review a studied topic everyday for a week, you'll have to specify there are 7 reviews and then type the following numbers: 1,2,3,4,5,6,7.",
        addCustomizedReviewsWarning: 'This customized reviews will be added permanently',
        numberOfReviews: 'Number of reviews',
        areYouSureYouWantToDeleteThisTopic: 'Are you sure you want to delete this topic?',
        deleteTopicWarning: '(This will permanently remove this topic along its references and its reviews)',
        ref: 'References',
        areYouSureYouWantToDeleteYourCompletedTopics: 'Are you sure you want to delete your completed topics?',
        deleteCompletedTopicsWarning: '(This will permanently remove the topics wich reviews are already completed)',
        deleteHistory: 'Delete history',
        deleteMissedSessions: 'Delete missed reviews',
        completedReview: 'Completed review' ,
        initialStudySession: 'Initial study session',
        reviewToBeDone: 'Review to be done',
        reviewNotDone: 'Review not done',
        pomodoroTimer: 'Pomodoro timer',
        focus: 'Focus',
        sessionsToBeDone: 'Sessions to be done',
        focusTime: 'Focus time',
        shortRest: 'Short rest',
        longRest: 'Long rest',
        sessionsBeforeLongRest: 'Sessions before long rest'
    }
}

export default Languages